import type { CodeSample } from "../LanguageIsThePromptPage";

export interface CodeSampleSpec extends Omit<CodeSample, "snippets"> {
  snippetPaths: Record<string, string>;
}

// Generated by /scripts/extract-language-samples.mjs
export const codeSamplesSpec: CodeSampleSpec[] = [
/* ── 1. Pattern Matching ── */
{
    id: "pattern-matching",
    title: { en: "Pattern Matching", ja: "パターンマッチング" },
    description: {
        en: "Algebraic data decomposition -instead of testing conditions imperatively, you declare the shape of data each branch handles, and the compiler guarantees exhaustiveness. The paper found function-head dispatch eliminates hidden control flow, making each branch a self-contained, locally predictable unit for LLMs. Below: Elixir multi-clause function heads, Python 3.10+ structural matching, Kotlin sealed-class when, TypeScript discriminated unions, and more.",
        ja: "代数的データ分解 -命令的に条件をテストする代わりに、各分岐が処理するデータの形状を宣言し、コンパイラが網羅性を保証する。論文では関数ヘッドディスパッチが隠れた制御フローを排除し、各分岐がLLMにとって自己完結した予測可能な単位になることを発見。以下：Elixirの複数句関数ヘッド、Python 3.10+構造的マッチ、Kotlinのsealed class + when、TypeScriptの判別共用体など。",
    },
    importance: "high",
    icon: "git-branch",
    libraries: [
        { lang: "python", name: "match statement (3.10+)", url: "https://docs.python.org/3/reference/compound_stmts.html#the-match-statement", builtin: true },
        { lang: "typescript", name: "Discriminated unions", url: "https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions", builtin: true },
        { lang: "typescript_effect", name: "Match.tag + Schema.TaggedClass (v4 beta)", url: "https://effect.website/docs/data-types/match" },
        { lang: "go", name: "Type switch", url: "https://go.dev/tour/methods/16", builtin: true },
        { lang: "csharp", name: "Switch expressions (C# 8+)", url: "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression", builtin: true },
        { lang: "dart", name: "Switch expressions (Dart 3.0+)", url: "https://dart.dev/language/branches#switch-expressions", builtin: true },
        { lang: "swift", name: "switch + pattern matching", url: "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/#Switch", builtin: true },
        { lang: "kotlin", name: "sealed class + when", url: "https://kotlinlang.org/docs/sealed-classes.html", builtin: true },
    ],
    caveats: {
        en: "Python structural pattern matching requires 3.10+. Dart switch expressions require Dart 3.0+. C# switch expressions require C# 8+.",
        ja: "Pythonの構造的パターンマッチには3.10+が必要。Dartのswitch式にはDart 3.0+が必要。C#のswitch式にはC# 8+が必要。",
    },
    annotations: {
        elixir: [
            {
                match: "def area(",
                title: { en: "Pattern matching starts in the head", ja: "パターンマッチは関数ヘッドから始まる" },
                body: {
                    en: "Elixir chooses the clause before entering the body. You do not scan for a later `if`, `switch`, or `match` to discover the branch.",
                    ja: "Elixirでは関数本体に入る前に節が選ばれる。後から `if` や `switch` を探して分岐を理解する必要がない。",
                },
            },
            {
                match: "{:circle, r}",
                title: { en: "Tag + destructure in one move", ja: "タグ判定と分解を同時に行う" },
                body: {
                    en: "The `:circle` atom picks the variant, and `r` becomes the radius immediately. The code both checks shape and pulls out data in the same syntax.",
                    ja: "`:circle` アトムでバリアントを選び、同時に `r` が半径として束縛される。形の判定とデータ取り出しが同じ構文で済む。",
                },
            },
            {
                match: "def area({:rect, w, h})",
                title: { en: "Each case gets its own clause", ja: "各ケースが独立した節になる" },
                body: {
                    en: "Circle, rect, and triangle are laid out as parallel clauses instead of one nested decision tree. The structure is repetitive and visually flat.",
                    ja: "circle / rect / triangle が、1つの深い分岐木ではなく並列な節として並ぶ。反復的で平坦な構造になっている。",
                },
            },
            {
                match: "Shape.area({:circle, 5})",
                title: { en: "The call site mirrors the clause", ja: "呼び出し側の形が節と対応する" },
                body: {
                    en: "Seeing `{:circle, 5}` at the call site already tells you which clause will execute. The data shape itself advertises the control flow.",
                    ja: "呼び出し側に `{:circle, 5}` が見えた時点で、どの節が実行されるかほぼ分かる。データの形そのものが制御フローを示している。",
                },
            },
        ],
    },
    snippetPaths: {
        csharp: "language-is-the-prompt/snippets/pattern-matching/csharp.cs",
        dart: "language-is-the-prompt/snippets/pattern-matching/dart.dart",
        elixir: "language-is-the-prompt/snippets/pattern-matching/elixir.ex",
        go: "language-is-the-prompt/snippets/pattern-matching/go.go",
        kotlin: "language-is-the-prompt/snippets/pattern-matching/kotlin.kt",
        python: "language-is-the-prompt/snippets/pattern-matching/python.py",
        swift: "language-is-the-prompt/snippets/pattern-matching/swift.swift",
        typescript: "language-is-the-prompt/snippets/pattern-matching/typescript.ts",
        typescript_effect: "language-is-the-prompt/snippets/pattern-matching/typescript_effect.ts"
    }
},
/* ── 2. Result Types / Tagged Tuples ── */
{
    id: "result-types",
    title: { en: "Result Types & Error Handling", ja: "Result型とエラーハンドリング" },
    description: {
        en: "Explicit error types formalize success vs. failure at the type level -a function's signature tells you exactly what can go wrong, rather than hiding exceptions in the call stack. The paper identified this as the single strongest cross-language predictor of LLM performance: every language scoring above 70% Pass@1 had idiomatic result types. Below: Elixir's {:ok, val}/{:error, reason} tuples, Swift/Kotlin Result and Arrow Either, Go's (value, error) pairs, Effect's typed error channel, and library-based approaches for Python, TypeScript, C#, and Dart.",
        ja: "明示的なエラー型は成功と失敗の区別を型レベルで形式化する -関数シグネチャが失敗の可能性を正確に伝え、コールスタックに例外を隠さない。論文ではこれが最も強力な言語横断的LLM性能予測因子と特定：Pass@1が70%超のすべての言語は慣用的なResult型を持っていた。以下：Elixirの{:ok, val}/{:error, reason}タプル、Swift/KotlinのResultとArrow Either、Goの(value, error)ペア、Effectの型付きエラーチャネル、Python・TypeScript・C#・Dartのライブラリベースのアプローチ。",
    },
    importance: "critical",
    icon: "shield",
    libraries: [
        { lang: "python", name: "returns", url: "https://github.com/dry-python/returns" },
        { lang: "typescript", name: "neverthrow", url: "https://github.com/supermacro/neverthrow" },
        { lang: "typescript_effect", name: "Schema.TaggedErrorClass + ServiceMap.Service (v4 beta)", url: "https://effect.website/docs/getting-started/running-effects" },
        { lang: "go", name: "(value, error) tuple", url: "https://go.dev/blog/error-handling-and-go", builtin: true },
        { lang: "csharp", name: "Result<T> (manual / CSharpFunctionalExtensions)", url: "https://github.com/vkhorikov/CSharpFunctionalExtensions" },
        { lang: "dart", name: "fpdart", url: "https://pub.dev/packages/fpdart" },
        { lang: "swift", name: "Result<Success, Failure>", url: "https://developer.apple.com/documentation/swift/result", builtin: true },
        { lang: "kotlin", name: "Arrow Either", url: "https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core/-either/" },
    ],
    caveats: {
        en: "Python returns library provides monadic Result; native Python has no built-in Result type. TypeScript has no native Result -neverthrow or manual discriminated unions. C# sample uses a manual Result record; consider CSharpFunctionalExtensions for production use.",
        ja: "Pythonのreturnsライブラリはモナド的Resultを提供。ネイティブPythonにはResult型がない。TypeScriptにもネイティブResultはなく、neverthrowまたは手動の判別共用体を使用。C#サンプルは手動Result record。本番にはCSharpFunctionalExtensionsも検討を。",
    },
    annotations: {
        elixir: [
            {
                match: "nil   -> {:error, :not_found}",
                title: { en: "Failure is returned as data", ja: "失敗もデータとして返す" },
                body: {
                    en: "A missing user does not throw. The branch returns a tagged tuple that every caller can pattern-match on explicitly.",
                    ja: "ユーザー未発見でも例外は投げず、タグ付きタプルを返す。呼び出し側はその形をそのままパターンマッチできる。",
                },
            },
            {
                match: "with {:ok, user}    <- fetch_user(user_id),",
                title: { en: "Happy path reads top to bottom", ja: "ハッピーパスが上から下へ読める" },
                body: {
                    en: "Each `<-` step expects `{:ok, value}` and binds the value only on success. The chain stops automatically on the first non-matching result.",
                    ja: "各 `<-` は `{:ok, value}` を期待し、成功時だけ値を束縛する。形が合わなければその時点で自動的に連鎖が止まる。",
                },
            },
            {
                match: "User.changeset(user, %{email: new_email})",
                title: { en: "Validation stays in the same data flow", ja: "バリデーションも同じデータフローに乗る" },
                body: {
                    en: "Building the changeset and persisting it remain ordinary tuple-producing steps. Validation is not a hidden side channel.",
                    ja: "changeset の生成と保存も、通常のタプルを返すステップとして連鎖に残る。検証が隠れた副経路にならない。",
                },
            },
            {
                match: "{:error, changeset}  -> {:error, format_errors(changeset)}",
                title: { en: "Errors can be normalized at the boundary", ja: "エラーは境界で正規化できる" },
                body: {
                    en: "The raw failure shape from deeper layers is converted into a caller-friendly error right in the `else` branch, without exceptions or out-of-band control flow.",
                    ja: "下位層の失敗形を `else` 側で呼び出し側向けのエラーへ変換できる。例外や別経路の制御フローは不要。",
                },
            },
        ],
    },
    snippetPaths: {
        csharp: "language-is-the-prompt/snippets/result-types/csharp.cs",
        dart: "language-is-the-prompt/snippets/result-types/dart.dart",
        elixir: "language-is-the-prompt/snippets/result-types/elixir.ex",
        go: "language-is-the-prompt/snippets/result-types/go.go",
        kotlin: "language-is-the-prompt/snippets/result-types/kotlin.kt",
        python: "language-is-the-prompt/snippets/result-types/python.py",
        swift: "language-is-the-prompt/snippets/result-types/swift.swift",
        typescript: "language-is-the-prompt/snippets/result-types/typescript.ts",
        typescript_effect: "language-is-the-prompt/snippets/result-types/typescript_effect.ts"
    }
},
/* ── 3. Immutability ── */
{
    id: "immutability",
    title: { en: "Immutability Default", ja: "デフォルト不変性" },
    description: {
        en: "Referential transparency -once a binding is established, it never changes. This is the foundation of equational reasoning (Backus 1978) and eliminates entire categories of bugs: stale references, aliasing hazards, time-of-check/time-of-use races. For LLMs, immutability means every value is defined exactly where it appears -no tracing mutation history across scopes. The paper found that languages with immutable-by-default semantics produced significantly fewer stateful bugs in generated code, because the model never needs to reason about 'which version of X am I looking at?'",
        ja: "参照透過性 -一度束縛された値は決して変わらない。等式推論（Backus 1978）の基盤であり、古参照・エイリアシング・TOCTOU競合を丸ごと排除する。LLMにとって不変性は、すべての値がその出現箇所で定義されることを意味し、スコープをまたぐ変異履歴の追跡が不要となる。論文では、デフォルト不変の言語が生成コードにおいて有意にステートフルバグを減らすことを確認 -モデルが「今見ているXはどのバージョンか」を推論する必要がないため。",
    },
    importance: "high",
    icon: "lock",
    libraries: [
        { lang: "elixir", name: "Immutable by default (all data)", url: "https://hexdocs.pm/elixir/basic-types.html", builtin: true },
        { lang: "python", name: "dataclasses(frozen=True)", url: "https://docs.python.org/3/library/dataclasses.html#frozen-instances", builtin: true },
        { lang: "typescript", name: "Readonly<T> + as const", url: "https://www.typescriptlang.org/docs/handbook/2/objects.html#readonly-properties", builtin: true },
        { lang: "typescript_effect", name: "Schema.Class (v4 beta immutable data)", url: "https://effect.website/docs/data-types/data" },
        { lang: "go", name: "Value types (struct copy semantics)", url: "https://go.dev/doc/effective_go#allocation_new", builtin: true },
        { lang: "csharp", name: "record + with expression (C# 9+)", url: "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record", builtin: true },
        { lang: "dart", name: "freezed code generation", url: "https://pub.dev/packages/freezed" },
        { lang: "swift", name: "struct (value type) + let bindings", url: "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/classesandstructures/", builtin: true },
        { lang: "kotlin", name: "data class + copy()", url: "https://kotlinlang.org/docs/data-classes.html#copying", builtin: true },
    ],
    caveats: {
        en: "Elixir, Erlang, and Haskell are truly immutable by default -all others require opt-in. Python frozen dataclasses are shallow-frozen only. TypeScript Readonly is a compile-time check only (no runtime enforcement). Go struct copies are shallow -nested pointers still alias. Dart requires codegen (freezed) for deep immutability. Swift structs are value types but classes are reference types.",
        ja: "Elixir・Erlang・Haskellのみが真のデフォルト不変 -他はすべてオプトイン。Pythonのfrozen dataclassは浅いフリーズのみ。TypeScriptのReadonlyはコンパイル時チェックのみ（実行時は未保証）。Goの構造体コピーは浅く、ネストしたポインタはエイリアスする。Dartは深い不変性にコード生成（freezed）が必要。Swiftのstructは値型だがclassは参照型。",
    },
    annotations: {
        elixir: [
            {
                match: "next = state.count + 1",
                title: { en: "You derive a new value, not mutate the old one", ja: "既存値を変更せず、新しい値を導く" },
                body: {
                    en: "The next count is computed into a fresh binding. `state.count` itself never changes anywhere in the function.",
                    ja: "次の値は新しい束縛 `next` に計算される。`state.count` 自体は関数内のどこでも書き換わらない。",
                },
            },
            {
                match: "| count: next,",
                title: { en: "Struct/map update copies with one field changed", ja: "マップ更新は差分だけ変えた新しい値を作る" },
                body: {
                    en: "The `%{state | ...}` form reuses the old map shape while producing a new value. It reads like “same state, except these fields”.",
                    ja: "`%{state | ...}` は元のマップ形を保ちながら新しい値を返す。「同じ state だが、この項目だけ違う」と読める。",
                },
            },
            {
                match: "history: state.history ++ [next]",
                title: { en: "Collection growth is explicit data construction", ja: "コレクション更新も明示的なデータ構築" },
                body: {
                    en: "Appending history creates the next list in place of mutating a hidden buffer. The new state shows exactly where the extra item came from.",
                    ja: "履歴追加も隠れたバッファ更新ではなく、新しいリストを明示的に組み立てる。追加要素の出所がコード上で見える。",
                },
            },
            {
                match: "state.count      # => 0",
                title: { en: "The old value remains valid after the call", ja: "呼び出し後も元の値はそのまま有効" },
                body: {
                    en: "The example proves immutability directly: after `Counter.increment(state)`, the original `state` still reports `0`.",
                    ja: "この例は不変性をそのまま示している。`Counter.increment(state)` の後でも元の `state` は `0` のまま。",
                },
            },
        ],
    },
    snippetPaths: {
        csharp: "language-is-the-prompt/snippets/immutability/csharp.cs",
        dart: "language-is-the-prompt/snippets/immutability/dart.dart",
        elixir: "language-is-the-prompt/snippets/immutability/elixir.ex",
        go: "language-is-the-prompt/snippets/immutability/go.go",
        kotlin: "language-is-the-prompt/snippets/immutability/kotlin.kt",
        python: "language-is-the-prompt/snippets/immutability/python.py",
        swift: "language-is-the-prompt/snippets/immutability/swift.swift",
        typescript: "language-is-the-prompt/snippets/immutability/typescript.ts",
        typescript_effect: "language-is-the-prompt/snippets/immutability/typescript_effect.ts"
    }
},
/* ── 4. Pipe Operator ── */
{
    id: "pipe-operator",
    title: { en: "Pipe Operator & Data Pipelines", ja: "パイプ演算子とデータパイプライン" },
    description: {
        en: "Pipeline composition expresses data transformation as a linear sequence -the dual of deeply nested function calls. In CS terms, this is function composition (f ∘ g ∘ h) made human-readable. The paper found pipeline style correlates with lower prediction entropy: each step is context-independent, so the model only needs local understanding. Below: Elixir's native |>, method chaining in OOP ecosystems, Effect's pipe() (since TC39 pipe is still Stage 2), and explicit staging in Go.",
        ja: "パイプライン合成はデータ変換を線形シーケンスで表現する -深くネストした関数呼び出しの双対。CS的には関数合成(f ∘ g ∘ h)の人間可読版。論文ではパイプラインスタイルが予測エントロピー低下と相関：各ステップがコンテキスト独立で、モデルはローカルな理解だけで予測できる。以下：Elixirのネイティブ|>、OOPでのメソッドチェーン、EffectのTC39 Stage 2待ちpipe()、Goの明示的ステージング。",
    },
    importance: "high",
    icon: "layers",
    libraries: [
        { lang: "python", name: "toolz pipe()", url: "https://toolz.readthedocs.io/en/latest/api.html#toolz.functoolz.pipe" },
        { lang: "typescript", name: "Array method chains", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#instance_methods", builtin: true },
        { lang: "typescript_effect", name: "pipe()", url: "https://effect.website/docs/getting-started/the-pipe-function" },
        { lang: "go", name: "Explicit variables (idiomatic)", url: "https://go.dev/doc/effective_go#named-results", builtin: true },
        { lang: "csharp", name: "LINQ method chains", url: "https://learn.microsoft.com/en-us/dotnet/csharp/linq/", builtin: true },
        { lang: "dart", name: "Cascade (..) notation", url: "https://dart.dev/language/operators#cascade-notation", builtin: true },
        { lang: "swift", name: "Method chaining", url: "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/methods/", builtin: true },
        { lang: "kotlin", name: "let / run scope functions", url: "https://kotlinlang.org/docs/scope-functions.html", builtin: true },
    ],
    caveats: {
        en: "TC39 Pipe Operator (|>) proposal is at Stage 2 -current Node/Bun/Deno do not ship it natively. Effect's pipe() is the recommended workaround for TypeScript. Python's toolz.pipe() is a third-party utility; most Python code uses method chaining or intermediate variables.",
        ja: "TC39パイプ演算子(|>)提案はStage 2 -現行のNode/Bun/Denoはネイティブ未実装。Effectのpipe()がTypeScriptの推奨回避策。Pythonのtoolz.pipe()はサードパーティ。多くのPythonコードはメソッドチェーンまたは中間変数を使用。",
    },
    annotations: {
        elixir: [
            {
                match: "|> Enum.filter(&(&1.status == :completed))",
                title: { en: "Each pipe step names one transformation", ja: "各パイプが変換を一段ずつ示す" },
                body: {
                    en: "Filtering completed orders is its own line and its own operation. You do not have to mentally unwrap nested calls to find the first stage.",
                    ja: "完了注文の抽出が1行1操作として独立している。ネストをほどいて最初の処理を探す必要がない。",
                },
            },
            {
                match: "|> Enum.map(& &1.total)",
                title: { en: "Shape changes stay visible in sequence", ja: "データの形の変化が順番に見える" },
                body: {
                    en: "After filtering orders, the pipeline projects them down to totals. The reader can track the data shape one small step at a time.",
                    ja: "注文を絞った後、そのまま total の列へ写像している。データ形の変化を小さな段階ごとに追える。",
                },
            },
            {
                match: "|> then(&(&1 * 1.1))",
                title: { en: "Ad hoc math still fits the pipeline", ja: "一時的な計算もパイプの中に収まる" },
                body: {
                    en: "When no named function exists, `then/2` inserts a tiny anonymous step without breaking the left-to-right flow.",
                    ja: "専用関数がなくても `then/2` で小さな匿名処理を差し込める。左から右の流れは崩れない。",
                },
            },
            {
                match: "|> String.replace(~r/[^a-z0-9\\\\s]/, \"\")",
                title: { en: "The same pattern scales to text pipelines", ja: "同じ形を文字列処理にもそのまま使える" },
                body: {
                    en: "The second example shows the exact same grammar applied to strings: trim, lowercase, clean, split, join. The visual pattern stays stable across domains.",
                    ja: "2つ目の例では同じ文法が文字列処理にもそのまま使われる。trim, lowercase, clean, split, join と視覚パターンが変わらない。",
                },
            },
        ],
    },
    snippetPaths: {
        csharp: "language-is-the-prompt/snippets/pipe-operator/csharp.cs",
        dart: "language-is-the-prompt/snippets/pipe-operator/dart.dart",
        elixir: "language-is-the-prompt/snippets/pipe-operator/elixir.ex",
        go: "language-is-the-prompt/snippets/pipe-operator/go.go",
        kotlin: "language-is-the-prompt/snippets/pipe-operator/kotlin.kt",
        python: "language-is-the-prompt/snippets/pipe-operator/python.py",
        swift: "language-is-the-prompt/snippets/pipe-operator/swift.swift",
        typescript: "language-is-the-prompt/snippets/pipe-operator/typescript.ts",
        typescript_effect: "language-is-the-prompt/snippets/pipe-operator/typescript_effect.ts"
    }
},
/* ── 5. Formatter Uniformity ── */
{
    id: "formatter-uniformity",
    title: { en: "Formatter Uniformity", ja: "フォーマッタ統一" },
    description: {
        en: "A canonical, zero-config formatter collapses surface-level entropy to near zero. In information-theoretic terms (Shannon 1948), if all projects look identical after formatting, the model spends zero predictive capacity on style and allocates 100% to semantics. Elixir ships mix format built-in -formatting is not a choice but a property of the ecosystem. The paper observed that consistent formatting across training data significantly reduces token-level perplexity, meaning the LLM wastes fewer parameters modeling whitespace, brace placement, and import ordering. Below: each language's current best opinionated formatter.",
        ja: "標準のゼロコンフィグフォーマッタが表面レベルのエントロピーをほぼゼロに圧縮する。情報理論（Shannon 1948）の観点では、全プロジェクトがフォーマット後に同一に見えれば、モデルはスタイルに予測容量をゼロ消費し、100%をセマンティクスに割り当てる。Elixirはmix formatを組み込みで提供 -フォーマットは選択ではなくエコシステムの性質。論文では、訓練データ全体の一貫したフォーマットがトークンレベルのパープレキシティを有意に低下させ、LLMが空白・括弧配置・import順序のモデリングに浪費するパラメータが減ることを確認。",
    },
    importance: "high",
    icon: "paintbrush",
    libraries: [
        { lang: "elixir", name: "mix format (built-in)", url: "https://hexdocs.pm/mix/Mix.Tasks.Format.html", builtin: true },
        { lang: "python", name: "ruff format", url: "https://docs.astral.sh/ruff/formatter/" },
        { lang: "typescript", name: "oxfmt (Oxc project)", url: "https://oxc.rs/docs/guide/usage/formatter" },
        { lang: "typescript_effect", name: "oxfmt (Oxc project)", url: "https://oxc.rs/docs/guide/usage/formatter" },
        { lang: "go", name: "gofumpt (stricter gofmt)", url: "https://github.com/mvdan/gofumpt" },
        { lang: "csharp", name: "CSharpier", url: "https://csharpier.com/" },
        { lang: "dart", name: "dart format (built-in)", url: "https://dart.dev/tools/dart-format", builtin: true },
        { lang: "swift", name: "swift-format", url: "https://github.com/swiftlang/swift-format" },
        { lang: "kotlin", name: "ktfmt", url: "https://github.com/facebook/ktfmt" },
    ],
    caveats: {
        en: "Only Elixir (mix format), Go (gofmt), and Dart (dart format) ship built-in formatters with zero config. Python migrated from Black to the faster Ruff. TypeScript ecosystem is shifting from Prettier to Rust-native oxfmt (Oxc). Go's gofumpt adds stricter rules on top of gofmt. Swift-format is official but not bundled with the compiler. Kotlin has multiple competing formatters (ktfmt, ktlint, IntelliJ built-in).",
        ja: "Elixir（mix format）・Go（gofmt）・Dart（dart format）のみがゼロコンフィグの組み込みフォーマッタを提供。PythonはBlackからより高速なRuffに移行中。TypeScriptエコシステムはPrettierからRustネイティブのoxfmt（Oxc）へシフト中。Goのgofumptはgofmtの上により厳密なルールを追加。swift-formatは公式だがコンパイラには同梱されず。Kotlinには複数の競合フォーマッタ（ktfmt, ktlint, IntelliJ組み込み）がある。",
    },
    annotations: {
        elixir: [
            {
                match: "mix format",
                title: { en: "Formatting is part of the language workflow", ja: "フォーマットが言語ワークフローに組み込まれている" },
                body: {
                    en: "Elixir’s canonical formatter ships with the toolchain. Teams do not need to negotiate style before they can share code that looks familiar.",
                    ja: "Elixir の標準フォーマッタはツールチェーン同梱。見慣れた形のコードを共有する前に、チームでスタイル交渉する必要がない。",
                },
            },
            {
                match: "%{",
                title: { en: "Composite literals get one predictable layout", ja: "複合リテラルの配置が一貫する" },
                body: {
                    en: "The map opens into a standard multiline shape with aligned fields. Readers learn one house style and see it everywhere.",
                    ja: "マップは標準的な複数行レイアウトに展開され、項目配置も揃う。読む側は1つの様式を覚えればよい。",
                },
            },
            {
                match: "email: email |> String.trim() |> String.downcase(),",
                title: { en: "Even dense expressions keep a normalized form", ja: "密な式でも正規化された形を保つ" },
                body: {
                    en: "A short pipeline stays inline here because it still fits the formatter’s rules. The shape is decided mechanically, not by personal taste.",
                    ja: "この短いパイプラインはフォーマッタ規則に従ってインラインのまま保たれる。見た目は好みではなく機械的に決まる。",
                },
            },
            {
                match: "tags: [\"active\", if(admin?, do: \"staff\", else: \"member\")]",
                title: { en: "Inline conditionals are rendered consistently too", ja: "インライン条件式も同じく一貫して整形される" },
                body: {
                    en: "The formatter preserves the compact `if(..., do:, else:)` idiom in a stable way. Special forms do not create style divergence across projects.",
                    ja: "コンパクトな `if(..., do:, else:)` も安定した形で整形される。特殊フォームがプロジェクトごとの見た目差を生みにくい。",
                },
            },
        ],
    },
    snippetPaths: {
        csharp: "language-is-the-prompt/snippets/formatter-uniformity/csharp.cs",
        dart: "language-is-the-prompt/snippets/formatter-uniformity/dart.dart",
        elixir: "language-is-the-prompt/snippets/formatter-uniformity/elixir.ex",
        go: "language-is-the-prompt/snippets/formatter-uniformity/go.go",
        kotlin: "language-is-the-prompt/snippets/formatter-uniformity/kotlin.kt",
        python: "language-is-the-prompt/snippets/formatter-uniformity/python.py",
        swift: "language-is-the-prompt/snippets/formatter-uniformity/swift.swift",
        typescript: "language-is-the-prompt/snippets/formatter-uniformity/typescript.ts",
        typescript_effect: "language-is-the-prompt/snippets/formatter-uniformity/typescript_effect.ts"
    }
},
/* ── 6. Happy Path Chaining ── */
{
    id: "with-statement",
    title: { en: "Happy Path Chaining & Short-Circuiting", ja: "ハッピーパスの連鎖とショートサーキット" },
    description: {
        en: "Monadic composition (>>= / bind) sequences fallible operations so that the first failure short-circuits the entire chain -no nested if-checks required. In CS terms, this is the Either monad applied to real workflow orchestration. The paper found that multi-step pipelines with explicit error propagation produce dramatically higher pass rates: LLMs generate each step as an independent unit, and the short-circuit semantics are trivially predictable. Below: Elixir with/else, Python returns.do, TypeScript early returns, Effect generators, and each language's idiomatic chaining.",
        ja: "モナド合成（>>= / bind）が失敗可能な操作を順序立て、最初の失敗でチェーン全体をショートサーキットする -ネストしたif文不要。CS的にはEitherモナドを実ワークフローオーケストレーションに適用したもの。論文では、明示的エラー伝播を伴う多段パイプラインが劇的に高いPass率を生むことを発見：LLMは各ステップを独立ユニットとして生成し、ショートサーキットセマンティクスは自明に予測可能。",
    },
    importance: "high",
    icon: "sparkles",
    libraries: [
        { lang: "elixir", name: "with/else special form", url: "https://hexdocs.pm/elixir/Kernel.SpecialForms.html#with/1", builtin: true },
        { lang: "python", name: "returns Result.do", url: "https://returns.readthedocs.io/en/latest/pages/railway.html" },
        { lang: "typescript", name: "neverthrow andThen()", url: "https://github.com/supermacro/neverthrow#chaining" },
        { lang: "typescript_effect", name: "Effect.gen + Schema.TaggedErrorClass (v4 beta)", url: "https://effect.website/docs/getting-started/using-generators" },
        { lang: "go", name: "Sequential if err != nil", url: "https://go.dev/blog/error-handling-and-go", builtin: true },
        { lang: "csharp", name: "CSharpFunctionalExtensions Bind", url: "https://github.com/vkhorikov/CSharpFunctionalExtensions" },
        { lang: "dart", name: "fpdart flatMap", url: "https://pub.dev/packages/fpdart" },
        { lang: "swift", name: "Result flatMap", url: "https://developer.apple.com/documentation/swift/result/flatmap(_:)", builtin: true },
        { lang: "kotlin", name: "Arrow either { } / bind()", url: "https://arrow-kt.io/docs/apidocs/arrow-core/arrow.core/-either/" },
    ],
    caveats: {
        en: "Python returns.do requires dry-python/returns ≥ 0.22. TypeScript lacks native monadic chaining -manual early returns or neverthrow .andThen() chains are the standard workaround. Effect.gen uses generators to simulate do-notation.",
        ja: "Python returns.doにはdry-python/returns ≥ 0.22が必要。TypeScriptにはネイティブのモナド連鎖がなく、手動の早期returnまたはneverthrow .andThen()チェーンが標準的な回避策。Effect.genはジェネレータでdo記法をシミュレートする。",
    },
    annotations: {
        elixir: [
            {
                match: "with {:ok, user}     <- authenticate(token),",
                title: { en: "The workflow declares its success contract up front", ja: "成功条件を最初に宣言している" },
                body: {
                    en: "Each line says “continue only if this step returns `{:ok, ...}`”. The happy path is encoded structurally, not implied by convention.",
                    ja: "各行が「このステップが `{:ok, ...}` を返した時だけ続行」と宣言している。成功経路が慣習ではなく構造として表現される。",
                },
            },
            {
                match: "{:ok, payment}  <- charge_card(user, items),",
                title: { en: "Later steps can use earlier bindings directly", ja: "後続ステップは前段の束縛をそのまま使える" },
                body: {
                    en: "By the time payment runs, `user` and `items` are already guaranteed-good values. No extra null checks or success flags clutter the call.",
                    ja: "payment の時点では `user` と `items` はすでに成功確定済み。追加の null チェックや成功フラグは不要。",
                },
            },
            {
                match: "send_confirmation(user, order)",
                title: { en: "Side effects happen only after the full chain succeeds", ja: "副作用は全工程成功後にだけ実行される" },
                body: {
                    en: "Confirmation sits inside the `do` block after every fallible step. That makes its preconditions obvious at a glance.",
                    ja: "確認送信は、失敗しうる全ステップの後に `do` ブロック内で実行される。前提条件が一目で分かる。",
                },
            },
            {
                match: "else",
                title: { en: "All failure exits are centralized", ja: "失敗出口が1か所に集約される" },
                body: {
                    en: "The `else` block is the single place where non-matching results are translated into user-facing errors. Recovery logic does not leak into the happy path.",
                    ja: "`else` は不一致結果をユーザー向けエラーへ変換する唯一の場所。回復ロジックがハッピーパス側へ漏れない。",
                },
            },
        ],
    },
    snippetPaths: {
        csharp: "language-is-the-prompt/snippets/with-statement/csharp.cs",
        dart: "language-is-the-prompt/snippets/with-statement/dart.dart",
        elixir: "language-is-the-prompt/snippets/with-statement/elixir.ex",
        go: "language-is-the-prompt/snippets/with-statement/go.go",
        kotlin: "language-is-the-prompt/snippets/with-statement/kotlin.kt",
        python: "language-is-the-prompt/snippets/with-statement/python.py",
        swift: "language-is-the-prompt/snippets/with-statement/swift.swift",
        typescript: "language-is-the-prompt/snippets/with-statement/typescript.ts",
        typescript_effect: "language-is-the-prompt/snippets/with-statement/typescript_effect.ts"
    }
},
/* ── 5. GenServer / Concurrency ── */
{
    id: "concurrency",
    title: { en: "Concurrency & State", ja: "並行処理と状態管理" },
    description: {
        en: "The actor model isolates mutable state inside a single-owner process that communicates only via message passing -no shared memory, no locks, no races by construction. In CS terms, this is Hewitt's actor model (1973) realized as a language primitive. The paper found this was the hardest domain across all languages: Elixir's GenServer scored 75% on hard concurrency tasks while most others dropped below 35%. The gap exists because GenServer's callback structure (init/handle_call/handle_cast) is a rigid, well-documented template that LLMs can fill in, whereas ad-hoc threading requires reasoning about non-local state mutations.",
        ja: "アクターモデルは可変状態を単一オーナープロセス内に隔離し、メッセージパッシングのみで通信する -共有メモリなし、ロックなし、構造的に競合なし。CS的にはHewittのアクターモデル（1973）を言語プリミティブとして実現したもの。論文ではこれが全言語で最も困難な領域であることを発見：Elixir GenServerは難しい並行処理タスクで75%を記録した一方、他のほとんどの言語は35%以下に低下。GenServerのコールバック構造（init/handle_call/handle_cast）が厳格で十分に文書化されたテンプレートでありLLMが穴埋めできるのに対し、アドホックなスレッディングは非局所的な状態変異の推論を必要とするためである。",
    },
    importance: "critical",
    icon: "cpu",
    libraries: [
        { lang: "elixir", name: "GenServer (OTP)", url: "https://hexdocs.pm/elixir/GenServer.html", builtin: true },
        { lang: "python", name: "asyncio.Queue + Task", url: "https://docs.python.org/3/library/asyncio-queue.html", builtin: true },
        { lang: "typescript", name: "Worker Threads", url: "https://nodejs.org/api/worker_threads.html", builtin: true },
        { lang: "typescript_effect", name: "Mailbox + Stream + Deferred", url: "https://effect.website/docs/concurrency/fibers" },
        { lang: "go", name: "goroutine + channel", url: "https://go.dev/doc/effective_go#goroutines", builtin: true },
        { lang: "csharp", name: "Channel<T> + Task", url: "https://learn.microsoft.com/en-us/dotnet/core/extensions/channels", builtin: true },
        { lang: "dart", name: "Isolate + SendPort", url: "https://dart.dev/language/concurrency", builtin: true },
        { lang: "swift", name: "actor (Swift 5.5+)", url: "https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency/#Actors", builtin: true },
        { lang: "kotlin", name: "Coroutines Channel", url: "https://kotlinlang.org/docs/channels.html" },
    ],
    caveats: {
        en: "Swift actors (5.5+) are the closest mainstream equivalent to GenServer -both enforce single-owner isolation. Go channels are lightweight but require manual select/done patterns. Python asyncio is single-threaded cooperative; true parallelism needs multiprocessing. Dart Isolates cannot share memory -communication is always via message ports.",
        ja: "Swiftのactor（5.5+）がGenServerに最も近い主流の等価物 -両者とも単一オーナー隔離を強制。Goチャネルは軽量だが手動のselect/doneパターンが必要。Python asyncioはシングルスレッド協調型で、真の並列性にはmultiprocessingが必要。Dart Isolateはメモリ共有不可 -通信は常にメッセージポート経由。",
    },
    annotations: {
        elixir: [
            {
                match: "use GenServer",
                title: { en: "The concurrency model is a named runtime primitive", ja: "並行モデルが名前付きのランタイム原語になっている" },
                body: {
                    en: "This is not a custom thread pattern. `GenServer` tells you immediately that the module follows a standard OTP process template with well-known callbacks.",
                    ja: "これは独自スレッド設計ではなく、標準OTPプロセステンプレートだと `GenServer` だけで分かる。コールバックも既知の形になる。",
                },
            },
            {
                match: "def increment, do: GenServer.call(__MODULE__, :increment)",
                title: { en: "The public API is just message sending", ja: "公開APIはメッセージ送信に薄く対応する" },
                body: {
                    en: "Client functions stay tiny because they only package requests. State access is never performed directly by outside callers.",
                    ja: "クライアント関数は要求を包むだけなので短い。外部呼び出し側が状態へ直接触ることはない。",
                },
            },
            {
                match: "def handle_call(:increment, _from, count),",
                title: { en: "State transitions live in explicit callbacks", ja: "状態遷移は明示的なコールバックに閉じ込められる" },
                body: {
                    en: "All logic for the `:increment` message is concentrated in the matching callback head. You can inspect one clause to understand one message.",
                    ja: "`:increment` に対するロジックが、このコールバックヘッドに集中している。1つのメッセージを理解するのに1つの節を読めばよい。",
                },
            },
            {
                match: "{:reply, count + 1, count + 1}",
                title: { en: "Reply and next state are returned together", ja: "返信値と次状態を同時に返す" },
                body: {
                    en: "The tuple spells out the protocol: what the caller gets back, and what state the server should keep. Mutation is made explicit as data.",
                    ja: "このタプルがプロトコルをそのまま示す。呼び出し側への返信と、サーバが保持すべき次状態が明示される。",
                },
            },
        ],
    },
    snippetPaths: {
        csharp: "language-is-the-prompt/snippets/concurrency/csharp.cs",
        dart: "language-is-the-prompt/snippets/concurrency/dart.dart",
        elixir: "language-is-the-prompt/snippets/concurrency/elixir.ex",
        go: "language-is-the-prompt/snippets/concurrency/go.go",
        kotlin: "language-is-the-prompt/snippets/concurrency/kotlin.kt",
        python: "language-is-the-prompt/snippets/concurrency/python.py",
        swift: "language-is-the-prompt/snippets/concurrency/swift.swift",
        typescript: "language-is-the-prompt/snippets/concurrency/typescript.ts",
        typescript_effect: "language-is-the-prompt/snippets/concurrency/typescript_effect.ts"
    }
},
/* ── 6. Doctests ── */
{
    id: "doctests",
    title: { en: "Executable Documentation", ja: "実行可能なドキュメント" },
    description: {
        en: "Literate programming -embedding runnable examples directly inside function documentation so that spec, test, and docs are a single artifact. Elixir's @doc + doctest runs examples as part of the test suite via ExUnit, creating verified input/output pairs co-located with the function definition. The paper found this uniquely beneficial for LLMs: when the training data contains thousands of functions with inline I/O examples, the model learns to treat documentation as executable specification rather than prose. Languages without native doctests approximate this through test-sourced documentation (DocFX, KDoc @sample, DocC @Snippet) -correct but less tightly co-located.",
        ja: "リテラルプログラミング -実行可能な例を関数ドキュメント内に直接埋め込み、仕様・テスト・ドキュメントを単一の成果物とする。Elixirの@doc + doctestはExUnitを介してテストスイートの一部として例を実行し、関数定義の隣に検証済みの入出力ペアを生成する。論文ではこれがLLMに特に有益であることを発見：訓練データにインラインI/O例付きの関数が何千も含まれると、モデルはドキュメントを散文ではなく実行可能な仕様として学習する。ネイティブdoctestを持たない言語はテストソース型ドキュメント（DocFX、KDoc @sample、DocC @Snippet）で近似する -正確だが共配置の緊密さは劣る。",
    },
    importance: "high",
    icon: "book-open",
    diagramId: "doc-pipeline",
    libraries: [
        { lang: "elixir", name: "ExUnit doctest", url: "https://hexdocs.pm/ex_unit/ExUnit.DocTest.html", builtin: true },
        { lang: "python", name: "doctest module", url: "https://docs.python.org/3/library/doctest.html", builtin: true },
        { lang: "typescript", name: "tsdoc + Vitest", url: "https://tsdoc.org/" },
        { lang: "typescript_effect", name: "@effect/vitest + JSDoc @example", url: "https://github.com/Effect-TS/effect/tree/main/packages/vitest" },
        { lang: "go", name: "Example functions (_test.go)", url: "https://go.dev/blog/examples", builtin: true },
        { lang: "csharp", name: "DocFX code snippets", url: "https://dotnet.github.io/docfx/" },
        { lang: "dart", name: "dartdoc_test", url: "https://pub.dev/packages/dartdoc_test" },
        { lang: "swift", name: "DocC @Snippet (Xcode 14+)", url: "https://developer.apple.com/documentation/docc" },
        { lang: "kotlin", name: "KDoc @sample", url: "https://kotlinlang.org/docs/kotlin-doc.html#sample-identifier" },
    ],
    caveats: {
        en: "Only Elixir, Python, Go, and Rust have truly native doctests that run as part of the standard test suite. TypeScript/JavaScript has no built-in doctest -various third-party tools exist but none are standard. Dart's dartdoc_test is a community package, not built-in. Swift DocC @Snippet compiles but doesn't assert return values. C# DocFX pulls source from test files -correct but indirect.",
        ja: "真にネイティブなdoctestを標準テストスイートの一部として実行できるのはElixir、Python、Go、Rustのみ。TypeScript/JavaScriptにはビルトインdoctestがなく、サードパーティツールが存在するが標準ではない。Dartのdartdoc_testはコミュニティパッケージ。Swift DocC @Snippetはコンパイルするが戻り値をアサートしない。C# DocFXはテストファイルからソースを取り込む -正確だが間接的。",
    },
    annotations: {
        elixir: [
            {
                match: "@doc \"\"\"",
                title: { en: "Examples live inside the official docs", ja: "公式ドキュメントの中に実例が入る" },
                body: {
                    en: "The primary documentation block is also where executable examples are written. Spec and example are co-located with the function.",
                    ja: "実行例は主要なドキュメントブロックの中に書かれる。仕様と例が関数の隣に共配置される。",
                },
            },
            {
                match: "iex> Math.safe_add(1, 2)",
                title: { en: "The docs show exact I/O, not vague prose", ja: "散文ではなく具体的な入出力を示す" },
                body: {
                    en: "An `iex>` example captures the function call exactly as a reader would try it. The expected result is right below it.",
                    ja: "`iex>` 例は、読者がそのまま試す呼び出し形を示す。期待結果も直下に並ぶ。",
                },
            },
            {
                match: "@spec safe_add(integer(), integer()) ::",
                title: { en: "Type-level contract and doc examples reinforce each other", ja: "型契約とドキュメント例が相互補強する" },
                body: {
                    en: "The `@spec` says the allowed result shapes, and the doctest demonstrates concrete instances of those shapes.",
                    ja: "`@spec` が許される結果形を示し、doctest がその具体例を示す。抽象契約と具体例が一致する。",
                },
            },
            {
                match: "doctest Math",
                title: { en: "One line turns the docs into test cases", ja: "1行でドキュメントがテストになる" },
                body: {
                    en: "This test declaration imports the examples from the docs and executes them under ExUnit. The examples are not decorative; they are enforced.",
                    ja: "この宣言がドキュメント例を ExUnit テストとして取り込み、実行する。例は飾りではなく検証対象になる。",
                },
            },
        ],
    },
    snippetPaths: {
        csharp: "language-is-the-prompt/snippets/doctests/csharp.cs",
        dart: "language-is-the-prompt/snippets/doctests/dart.dart",
        elixir: "language-is-the-prompt/snippets/doctests/elixir.ex",
        go: "language-is-the-prompt/snippets/doctests/go.go",
        kotlin: "language-is-the-prompt/snippets/doctests/kotlin.kt",
        python: "language-is-the-prompt/snippets/doctests/python.py",
        swift: "language-is-the-prompt/snippets/doctests/swift.swift",
        typescript: "language-is-the-prompt/snippets/doctests/typescript.ts",
        typescript_effect: "language-is-the-prompt/snippets/doctests/typescript_effect.ts"
    }
},
/* ── 7. Comprehensions with Filters ── */
{
    id: "comprehensions",
    title: { en: "Comprehensions & Generators", ja: "内包表記とジェネレータ" },
    description: {
        en: "List comprehensions are set-builder notation (∀x ∈ S, P(x) → f(x)) made executable -a declarative way to express map/filter/flatMap in a single construct. For LLMs, comprehensions are highly predictable because the entire transformation is specified in one syntactic unit with no hidden control flow. Elixir's for comprehension with <- generators, pattern-match filters, and :into collectors follows the same structure as mathematical set notation. Languages without native comprehensions approximate this through method chains (.map/.filter/.flatMap), LINQ query syntax, or sequence/yield builders.",
        ja: "リスト内包表記は集合構成記法（∀x ∈ S, P(x) → f(x)）を実行可能にしたもの -map/filter/flatMapを単一構文で宣言的に表現する方法。LLMにとって内包表記は非常に予測しやすい：変換全体が隠れた制御フローのない単一の構文単位で指定されるため。Elixirのfor内包表記は<-ジェネレータ、パターンマッチフィルタ、:intoコレクタで数学的集合記法と同じ構造に従う。ネイティブ内包表記を持たない言語はメソッドチェーン（.map/.filter/.flatMap）、LINQクエリ構文、sequence/yieldビルダで近似する。",
    },
    importance: "medium",
    icon: "flask-conical",
    libraries: [
        { lang: "elixir", name: "for comprehension", url: "https://hexdocs.pm/elixir/comprehensions.html", builtin: true },
        { lang: "python", name: "List/dict/set comprehensions", url: "https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions", builtin: true },
        { lang: "typescript", name: "Array .map/.filter/.flatMap", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#instance_methods", builtin: true },
        { lang: "typescript_effect", name: "Array.Do + Stream + Schema", url: "https://effect.website/docs/data-types/stream" },
        { lang: "go", name: "iter.Seq + slices package (Go 1.23+)", url: "https://pkg.go.dev/iter", builtin: true },
        { lang: "csharp", name: "LINQ query expressions", url: "https://learn.microsoft.com/en-us/dotnet/csharp/linq/get-started/query-expression-basics", builtin: true },
        { lang: "dart", name: "Collection-for + sync* generators", url: "https://dart.dev/language/collections#control-flow-operators", builtin: true },
        { lang: "swift", name: "lazy + compactMap chains", url: "https://developer.apple.com/documentation/swift/lazysequenceprotocol", builtin: true },
        { lang: "kotlin", name: "sequence { yield() } builder", url: "https://kotlinlang.org/docs/sequences.html#construct", builtin: true },
    ],
    caveats: {
        en: "Go lacked iterator protocol until 1.23 (iter.Seq). Dart collection-for (Dart 2.3+) is the closest to comprehension syntax. TypeScript has no comprehension syntax -method chains are idiomatic. C# LINQ from/where/select is syntactic sugar over .Select/.Where extension methods. Kotlin sequence builders use coroutines internally.",
        ja: "Goは1.23（iter.Seq）まで反復子プロトコルを欠いていた。Dartのcollection-for（Dart 2.3+）が内包表記構文に最も近い。TypeScriptには内包表記構文がなく、メソッドチェーンが慣用的。C# LINQのfrom/where/selectは.Select/.Where拡張メソッドのシンタックスシュガー。Kotlinのsequenceビルダは内部でコルーチンを使用する。",
    },
    annotations: {
        elixir: [
            {
                match: "for x <- 1..10,",
                title: { en: "Generators declare the input domains inline", ja: "ジェネレータが入力範囲をその場で宣言する" },
                body: {
                    en: "The comprehension starts by saying where `x` and `y` come from. Iteration source and result construction live in one syntactic unit.",
                    ja: "内包表記は `x` と `y` の出所を最初に宣言する。反復元と結果構築が1つの構文単位に収まる。",
                },
            },
            {
                match: "rem(x * y, 3) == 0",
                title: { en: "Filters sit next to the generators they constrain", ja: "フィルタが対象ジェネレータのすぐ横に置かれる" },
                body: {
                    en: "Instead of a nested `if`, the predicate appears directly inside the comprehension header. Selection rules stay local and declarative.",
                    ja: "入れ子の `if` ではなく、条件が内包表記ヘッダ内に直接書かれる。選別ルールがローカルで宣言的になる。",
                },
            },
            {
                match: "[name, score_text] = String.split(line, \",\", parts: 2),",
                title: { en: "Pattern matching can filter and destructure mid-stream", ja: "途中でパターンマッチによる分解と絞り込みができる" },
                body: {
                    en: "This line both asserts the split shape and binds its pieces. Inputs that do not match are discarded automatically from the comprehension.",
                    ja: "この行は分割結果の形を確認しつつ、要素を束縛する。形が合わない入力は内包表記から自動的に落ちる。",
                },
            },
            {
                match: "%{name: String.trim(name), score: score, grade: \"A\"}",
                title: { en: "The output expression is the final line of the construct", ja: "出力形が構文の最後に明示される" },
                body: {
                    en: "After generators and filters, the body says exactly what each kept item becomes. Input selection and output shape are visually adjacent.",
                    ja: "ジェネレータとフィルタの後に、採用された各要素が何になるかを最後の式で示す。入力条件と出力形が近接して見える。",
                },
            },
        ],
    },
    snippetPaths: {
        csharp: "language-is-the-prompt/snippets/comprehensions/csharp.cs",
        dart: "language-is-the-prompt/snippets/comprehensions/dart.dart",
        elixir: "language-is-the-prompt/snippets/comprehensions/elixir.ex",
        go: "language-is-the-prompt/snippets/comprehensions/go.go",
        kotlin: "language-is-the-prompt/snippets/comprehensions/kotlin.kt",
        python: "language-is-the-prompt/snippets/comprehensions/python.py",
        swift: "language-is-the-prompt/snippets/comprehensions/swift.swift",
        typescript: "language-is-the-prompt/snippets/comprehensions/typescript.ts",
        typescript_effect: "language-is-the-prompt/snippets/comprehensions/typescript_effect.ts"
    }
}
];
